[package]
name = "konsoleat"
version = "2.1.0"
edition = "2024"
description = "A tool that activates or creates a Konsole terminal session in a specified working directory"
repository = "https://github.com/antoniszymanski/konsoleat-rs"
license = "MPL-2.0"

[dependencies]
askama = "0.16.0"
clap = { version = "4.5.53", features = ["derive"] }
procfs = { version = "0.18.0", default-features = false }
same-file = "1.0.6"
snafu = "0.9.0"
tempfile = "3.24.0"
zbus = "5.12.0"
zbus_xml = "5.0.2"

[build-dependencies]
carapace_spec_clap = "1.2.3"
clap = { version = "4.5.53", features = ["derive"] }
clap_complete = "4.6.9"
clap_complete_nushell = "4.6.2"
clap_mangen = "0.3.3"
remove_dir_all = "1.0.0"

[profile.release]
lto = true
codegen-units = 1
